version: '3.8'

services:
  web:
    container_name: store_service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      run_db_migrations:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      celery:
        condition: service_started
      celery-beat:
        condition: service_started
      broker:
        condition: service_healthy
    networks:
      - app-network

  run_db_migrations:
    container_name: migrations
    build: .
    restart: no
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672/
    depends_on:
      db:
        condition: service_healthy
    command: "python /usr/src/server/main/manage.py migrate"
    networks:
      - app-network

  db:
    container_name: psql_db_store_service
    image: postgres:16.2
    restart: always
    user: postgres
    environment:
      - DOCKERIZED=true
      - POSTGRES_DB=docker_store_service
      - POSTGRES_PASSWORD=password
    expose:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  celery:
    container_name: celery
    build:
      context: .
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379
    command: celery -A core worker -l INFO
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - app-network

  celery-beat:
    container_name: celery_beat
    build:
      context: .
    env_file:
      - .env
    command: celery -A core beat --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - app-network

  broker:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 30s
      timeout: 30s
      retries: 10
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7.0-alpine
    restart: always
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  db-data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
