version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
#    command: "python /app/manage.py runserver_plus --cert-file cert.pem --key-file key.pem 0.0.0.0:8000"

  db:
    image: postgres:16.2
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=store_service
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db-data: