# Generated by Django 5.1 on 2024-08-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usersapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="invitation_code",
            new_name="referral_code",
        ),
    ]
