# Generated by Django 5.1 on 2024-08-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customobtaintoken",
            name="key",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
