# Generated by Django 5.1 on 2024-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customobtaintoken",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
