# Generated by Django 5.1 on 2024-08-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapi", "0002_alter_customobtaintoken_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="customobtaintoken",
            name="status",
            field=models.CharField(default="Online", max_length=15),
        ),
    ]
