# Generated by Django 5.1 on 2024-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapi", "0002_rename_invitation_code_customuser_referral_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_own_invite_code",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
