# Generated by Django 5.1 on 2024-09-04 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeapi", "0001_initial"),
        ("usersapi", "0003_alter_customuser_user_own_invite_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNFTBackpack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_products",
                        to="storeapi.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_backpack",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
