# Generated by Django 5.1 on 2024-11-20 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapi", "0004_usernftbackpack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customobtaintoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
