# Generated by Django 5.1 on 2024-08-29 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="wallet_balance",
            field=models.DecimalField(decimal_places=2, max_digits=15, default=0.00),
        ),
        migrations.CreateModel(
            name="WalletToWalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("wallet_addr_from", models.CharField(max_length=64)),
                ("wallet_addr_to", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("user_from", models.F("user_to")), _negated=True),
                        name="prevent_self_transfer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("wallet_addr_from", models.F("wallet_addr_to")),
                            _negated=True,
                        ),
                        name="prevent_same_wallet_transfer",
                    ),
                ],
            },
        ),
    ]
