# Generated by Django 5.1 on 2024-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="for_sale",
            field=models.BooleanField(default=True),
        ),
    ]
