# Generated by Django 5.1 on 2024-09-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeapi", "0002_product_for_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=127),
        ),
    ]
